from enum import Enum

class Grape(str, Enum):
    airen = "Airén"
    albarino = "Albariño"
    barbera = "Barbera"
    cabernet_franco = "Cabernet Franc"
    cabernet_sauvignon = "Cabernet Sauvignon"
    carmenere = "Caménère"
    chardonnay = "Chardonnay"
    chenin_blanc = "Chenin Blanc"
    colombard = "Colombard"
    gamay = "Gamay"
    garnacha = "Garnacha"
    gewurztraminer = "Gewürztraminer"
    macabeo = "Macabeo"
    malbec = "Malbec"
    merlot = "Merlot"
    monastrell = "Monastrell"
    moscato = "Moscato"
    nebbiolo = "Nebbiolo"
    pinot_grigio = "Pinot Grigio"
    pinot_noir = "Pinot Noir"
    riesling = "Riesling"
    sangiovese = "Sangiovese"
    sauvignon_blanc = "Sauvignon Blanc"
    semillon = "Semillon"
    syrah = "Syrah"
    tempranillo = "Tempranillo"
    touriga_nacional = "Touriga Nacional"
    trebbiano = "Trebbiano"
    verdejo = "Verdejo"
    viognier = "Viognier"
    zinfandel = "Zinfandel"